/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DemoTerraRouteImport } from './routes/demo.terra'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as WorldsWorldIdRouteImport } from './routes/worlds.$worldId'
import { Route as WorldsNewRouteImport } from './routes/worlds.new'
import { Route as WorldsTerraRouteImport } from './routes/worlds.terra'
import { Route as DemoTerraIndexRouteImport } from './routes/demo.terra.index'
import { Route as DemoTerraContinuityRouteImport } from './routes/demo.terra.continuity'
import { Route as DemoTerraKnowledgeRouteImport } from './routes/demo.terra.knowledge'
import { Route as DemoTerraLoreRouteImport } from './routes/demo.terra.lore'
import { Route as DemoTerraManuscriptRouteImport } from './routes/demo.terra.manuscript'
import { Route as DemoTerraNotesRouteImport } from './routes/demo.terra.notes'
import { Route as DemoTerraPlacesRouteImport } from './routes/demo.terra.places'
import { Route as DemoTerraRelationshipsRouteImport } from './routes/demo.terra.relationships'
import { Route as DemoTerraSecretsRouteImport } from './routes/demo.terra.secrets'
import { Route as DemoTerraTimelineRouteImport } from './routes/demo.terra.timeline'
import { Route as WorldsWorldIdManuscriptRouteImport } from './routes/worlds.$worldId.manuscript'
import { Route as WorldsTerraIndexRouteImport } from './routes/worlds.terra.index'
import { Route as WorldsTerraContinuityRouteImport } from './routes/worlds.terra.continuity'
import { Route as WorldsTerraKnowledgeRouteImport } from './routes/worlds.terra.knowledge'
import { Route as WorldsTerraLoreRouteImport } from './routes/worlds.terra.lore'
import { Route as WorldsTerraManuscriptRouteImport } from './routes/worlds.terra.manuscript'
import { Route as WorldsTerraNotesRouteImport } from './routes/worlds.terra.notes'
import { Route as WorldsTerraPlacesRouteImport } from './routes/worlds.terra.places'
import { Route as WorldsTerraRelationshipsRouteImport } from './routes/worlds.terra.relationships'
import { Route as WorldsTerraSecretsRouteImport } from './routes/worlds.terra.secrets'
import { Route as WorldsTerraSettingsRouteImport } from './routes/worlds.terra.settings'
import { Route as WorldsTerraTimelineRouteImport } from './routes/worlds.terra.timeline'
import { Route as DemoTerraCharactersIndexRouteImport } from './routes/demo.terra.characters.index'
import { Route as DemoTerraCharactersSlugRouteImport } from './routes/demo.terra.characters.$slug'
import { Route as WorldsTerraCharactersIndexRouteImport } from './routes/worlds.terra.characters.index'
import { Route as WorldsTerraCharactersSlugRouteImport } from './routes/worlds.terra.characters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTerraRoute = DemoTerraRouteImport.update({
  id: '/demo/terra',
  path: '/demo/terra',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/worlds/',
  path: '/worlds/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsWorldIdRoute = WorldsWorldIdRouteImport.update({
  id: '/worlds/$worldId',
  path: '/worlds/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsNewRoute = WorldsNewRouteImport.update({
  id: '/worlds/new',
  path: '/worlds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsTerraRoute = WorldsTerraRouteImport.update({
  id: '/worlds/terra',
  path: '/worlds/terra',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTerraIndexRoute = DemoTerraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraContinuityRoute = DemoTerraContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraKnowledgeRoute = DemoTerraKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraLoreRoute = DemoTerraLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraManuscriptRoute = DemoTerraManuscriptRouteImport.update({
  id: '/manuscript',
  path: '/manuscript',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraNotesRoute = DemoTerraNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraPlacesRoute = DemoTerraPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraRelationshipsRoute = DemoTerraRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraSecretsRoute = DemoTerraSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => DemoTerraRoute,
} as any)
const DemoTerraTimelineRoute = DemoTerraTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DemoTerraRoute,
} as any)
const WorldsWorldIdManuscriptRoute = WorldsWorldIdManuscriptRouteImport.update({
  id: '/manuscript',
  path: '/manuscript',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsTerraIndexRoute = WorldsTerraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraContinuityRoute = WorldsTerraContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraKnowledgeRoute = WorldsTerraKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraLoreRoute = WorldsTerraLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraManuscriptRoute = WorldsTerraManuscriptRouteImport.update({
  id: '/manuscript',
  path: '/manuscript',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraNotesRoute = WorldsTerraNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraPlacesRoute = WorldsTerraPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraRelationshipsRoute =
  WorldsTerraRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => WorldsTerraRoute,
  } as any)
const WorldsTerraSecretsRoute = WorldsTerraSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraSettingsRoute = WorldsTerraSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const WorldsTerraTimelineRoute = WorldsTerraTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => WorldsTerraRoute,
} as any)
const DemoTerraCharactersIndexRoute =
  DemoTerraCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => DemoTerraRoute,
  } as any)
const DemoTerraCharactersSlugRoute = DemoTerraCharactersSlugRouteImport.update({
  id: '/characters/$slug',
  path: '/characters/$slug',
  getParentRoute: () => DemoTerraRoute,
} as any)
const WorldsTerraCharactersIndexRoute =
  WorldsTerraCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => WorldsTerraRoute,
  } as any)
const WorldsTerraCharactersSlugRoute =
  WorldsTerraCharactersSlugRouteImport.update({
    id: '/characters/$slug',
    path: '/characters/$slug',
    getParentRoute: () => WorldsTerraRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/demo/terra': typeof DemoTerraRouteWithChildren
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/worlds/new': typeof WorldsNewRoute
  '/worlds/terra': typeof WorldsTerraRouteWithChildren
  '/worlds/': typeof WorldsIndexRoute
  '/demo/terra/continuity': typeof DemoTerraContinuityRoute
  '/demo/terra/knowledge': typeof DemoTerraKnowledgeRoute
  '/demo/terra/lore': typeof DemoTerraLoreRoute
  '/demo/terra/manuscript': typeof DemoTerraManuscriptRoute
  '/demo/terra/notes': typeof DemoTerraNotesRoute
  '/demo/terra/places': typeof DemoTerraPlacesRoute
  '/demo/terra/relationships': typeof DemoTerraRelationshipsRoute
  '/demo/terra/secrets': typeof DemoTerraSecretsRoute
  '/demo/terra/timeline': typeof DemoTerraTimelineRoute
  '/worlds/$worldId/manuscript': typeof WorldsWorldIdManuscriptRoute
  '/worlds/terra/continuity': typeof WorldsTerraContinuityRoute
  '/worlds/terra/knowledge': typeof WorldsTerraKnowledgeRoute
  '/worlds/terra/lore': typeof WorldsTerraLoreRoute
  '/worlds/terra/manuscript': typeof WorldsTerraManuscriptRoute
  '/worlds/terra/notes': typeof WorldsTerraNotesRoute
  '/worlds/terra/places': typeof WorldsTerraPlacesRoute
  '/worlds/terra/relationships': typeof WorldsTerraRelationshipsRoute
  '/worlds/terra/secrets': typeof WorldsTerraSecretsRoute
  '/worlds/terra/settings': typeof WorldsTerraSettingsRoute
  '/worlds/terra/timeline': typeof WorldsTerraTimelineRoute
  '/demo/terra/': typeof DemoTerraIndexRoute
  '/worlds/terra/': typeof WorldsTerraIndexRoute
  '/demo/terra/characters/$slug': typeof DemoTerraCharactersSlugRoute
  '/worlds/terra/characters/$slug': typeof WorldsTerraCharactersSlugRoute
  '/demo/terra/characters/': typeof DemoTerraCharactersIndexRoute
  '/worlds/terra/characters/': typeof WorldsTerraCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/worlds/new': typeof WorldsNewRoute
  '/worlds': typeof WorldsIndexRoute
  '/demo/terra/continuity': typeof DemoTerraContinuityRoute
  '/demo/terra/knowledge': typeof DemoTerraKnowledgeRoute
  '/demo/terra/lore': typeof DemoTerraLoreRoute
  '/demo/terra/manuscript': typeof DemoTerraManuscriptRoute
  '/demo/terra/notes': typeof DemoTerraNotesRoute
  '/demo/terra/places': typeof DemoTerraPlacesRoute
  '/demo/terra/relationships': typeof DemoTerraRelationshipsRoute
  '/demo/terra/secrets': typeof DemoTerraSecretsRoute
  '/demo/terra/timeline': typeof DemoTerraTimelineRoute
  '/worlds/$worldId/manuscript': typeof WorldsWorldIdManuscriptRoute
  '/worlds/terra/continuity': typeof WorldsTerraContinuityRoute
  '/worlds/terra/knowledge': typeof WorldsTerraKnowledgeRoute
  '/worlds/terra/lore': typeof WorldsTerraLoreRoute
  '/worlds/terra/manuscript': typeof WorldsTerraManuscriptRoute
  '/worlds/terra/notes': typeof WorldsTerraNotesRoute
  '/worlds/terra/places': typeof WorldsTerraPlacesRoute
  '/worlds/terra/relationships': typeof WorldsTerraRelationshipsRoute
  '/worlds/terra/secrets': typeof WorldsTerraSecretsRoute
  '/worlds/terra/settings': typeof WorldsTerraSettingsRoute
  '/worlds/terra/timeline': typeof WorldsTerraTimelineRoute
  '/demo/terra': typeof DemoTerraIndexRoute
  '/worlds/terra': typeof WorldsTerraIndexRoute
  '/demo/terra/characters/$slug': typeof DemoTerraCharactersSlugRoute
  '/worlds/terra/characters/$slug': typeof WorldsTerraCharactersSlugRoute
  '/demo/terra/characters': typeof DemoTerraCharactersIndexRoute
  '/worlds/terra/characters': typeof WorldsTerraCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/demo/terra': typeof DemoTerraRouteWithChildren
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/worlds/new': typeof WorldsNewRoute
  '/worlds/terra': typeof WorldsTerraRouteWithChildren
  '/worlds/': typeof WorldsIndexRoute
  '/demo/terra/continuity': typeof DemoTerraContinuityRoute
  '/demo/terra/knowledge': typeof DemoTerraKnowledgeRoute
  '/demo/terra/lore': typeof DemoTerraLoreRoute
  '/demo/terra/manuscript': typeof DemoTerraManuscriptRoute
  '/demo/terra/notes': typeof DemoTerraNotesRoute
  '/demo/terra/places': typeof DemoTerraPlacesRoute
  '/demo/terra/relationships': typeof DemoTerraRelationshipsRoute
  '/demo/terra/secrets': typeof DemoTerraSecretsRoute
  '/demo/terra/timeline': typeof DemoTerraTimelineRoute
  '/worlds/$worldId/manuscript': typeof WorldsWorldIdManuscriptRoute
  '/worlds/terra/continuity': typeof WorldsTerraContinuityRoute
  '/worlds/terra/knowledge': typeof WorldsTerraKnowledgeRoute
  '/worlds/terra/lore': typeof WorldsTerraLoreRoute
  '/worlds/terra/manuscript': typeof WorldsTerraManuscriptRoute
  '/worlds/terra/notes': typeof WorldsTerraNotesRoute
  '/worlds/terra/places': typeof WorldsTerraPlacesRoute
  '/worlds/terra/relationships': typeof WorldsTerraRelationshipsRoute
  '/worlds/terra/secrets': typeof WorldsTerraSecretsRoute
  '/worlds/terra/settings': typeof WorldsTerraSettingsRoute
  '/worlds/terra/timeline': typeof WorldsTerraTimelineRoute
  '/demo/terra/': typeof DemoTerraIndexRoute
  '/worlds/terra/': typeof WorldsTerraIndexRoute
  '/demo/terra/characters/$slug': typeof DemoTerraCharactersSlugRoute
  '/worlds/terra/characters/$slug': typeof WorldsTerraCharactersSlugRoute
  '/demo/terra/characters/': typeof DemoTerraCharactersIndexRoute
  '/worlds/terra/characters/': typeof WorldsTerraCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/demo/terra'
    | '/worlds/$worldId'
    | '/worlds/new'
    | '/worlds/terra'
    | '/worlds/'
    | '/demo/terra/continuity'
    | '/demo/terra/knowledge'
    | '/demo/terra/lore'
    | '/demo/terra/manuscript'
    | '/demo/terra/notes'
    | '/demo/terra/places'
    | '/demo/terra/relationships'
    | '/demo/terra/secrets'
    | '/demo/terra/timeline'
    | '/worlds/$worldId/manuscript'
    | '/worlds/terra/continuity'
    | '/worlds/terra/knowledge'
    | '/worlds/terra/lore'
    | '/worlds/terra/manuscript'
    | '/worlds/terra/notes'
    | '/worlds/terra/places'
    | '/worlds/terra/relationships'
    | '/worlds/terra/secrets'
    | '/worlds/terra/settings'
    | '/worlds/terra/timeline'
    | '/demo/terra/'
    | '/worlds/terra/'
    | '/demo/terra/characters/$slug'
    | '/worlds/terra/characters/$slug'
    | '/demo/terra/characters/'
    | '/worlds/terra/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/worlds/$worldId'
    | '/worlds/new'
    | '/worlds'
    | '/demo/terra/continuity'
    | '/demo/terra/knowledge'
    | '/demo/terra/lore'
    | '/demo/terra/manuscript'
    | '/demo/terra/notes'
    | '/demo/terra/places'
    | '/demo/terra/relationships'
    | '/demo/terra/secrets'
    | '/demo/terra/timeline'
    | '/worlds/$worldId/manuscript'
    | '/worlds/terra/continuity'
    | '/worlds/terra/knowledge'
    | '/worlds/terra/lore'
    | '/worlds/terra/manuscript'
    | '/worlds/terra/notes'
    | '/worlds/terra/places'
    | '/worlds/terra/relationships'
    | '/worlds/terra/secrets'
    | '/worlds/terra/settings'
    | '/worlds/terra/timeline'
    | '/demo/terra'
    | '/worlds/terra'
    | '/demo/terra/characters/$slug'
    | '/worlds/terra/characters/$slug'
    | '/demo/terra/characters'
    | '/worlds/terra/characters'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/demo/terra'
    | '/worlds/$worldId'
    | '/worlds/new'
    | '/worlds/terra'
    | '/worlds/'
    | '/demo/terra/continuity'
    | '/demo/terra/knowledge'
    | '/demo/terra/lore'
    | '/demo/terra/manuscript'
    | '/demo/terra/notes'
    | '/demo/terra/places'
    | '/demo/terra/relationships'
    | '/demo/terra/secrets'
    | '/demo/terra/timeline'
    | '/worlds/$worldId/manuscript'
    | '/worlds/terra/continuity'
    | '/worlds/terra/knowledge'
    | '/worlds/terra/lore'
    | '/worlds/terra/manuscript'
    | '/worlds/terra/notes'
    | '/worlds/terra/places'
    | '/worlds/terra/relationships'
    | '/worlds/terra/secrets'
    | '/worlds/terra/settings'
    | '/worlds/terra/timeline'
    | '/demo/terra/'
    | '/worlds/terra/'
    | '/demo/terra/characters/$slug'
    | '/worlds/terra/characters/$slug'
    | '/demo/terra/characters/'
    | '/worlds/terra/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DemoTerraRoute: typeof DemoTerraRouteWithChildren
  WorldsWorldIdRoute: typeof WorldsWorldIdRouteWithChildren
  WorldsNewRoute: typeof WorldsNewRoute
  WorldsTerraRoute: typeof WorldsTerraRouteWithChildren
  WorldsIndexRoute: typeof WorldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/terra': {
      id: '/demo/terra'
      path: '/demo/terra'
      fullPath: '/demo/terra'
      preLoaderRoute: typeof DemoTerraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/worlds'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$worldId': {
      id: '/worlds/$worldId'
      path: '/worlds/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof WorldsWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/new': {
      id: '/worlds/new'
      path: '/worlds/new'
      fullPath: '/worlds/new'
      preLoaderRoute: typeof WorldsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/terra': {
      id: '/worlds/terra'
      path: '/worlds/terra'
      fullPath: '/worlds/terra'
      preLoaderRoute: typeof WorldsTerraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/terra/': {
      id: '/demo/terra/'
      path: '/'
      fullPath: '/demo/terra/'
      preLoaderRoute: typeof DemoTerraIndexRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/continuity': {
      id: '/demo/terra/continuity'
      path: '/continuity'
      fullPath: '/demo/terra/continuity'
      preLoaderRoute: typeof DemoTerraContinuityRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/knowledge': {
      id: '/demo/terra/knowledge'
      path: '/knowledge'
      fullPath: '/demo/terra/knowledge'
      preLoaderRoute: typeof DemoTerraKnowledgeRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/lore': {
      id: '/demo/terra/lore'
      path: '/lore'
      fullPath: '/demo/terra/lore'
      preLoaderRoute: typeof DemoTerraLoreRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/manuscript': {
      id: '/demo/terra/manuscript'
      path: '/manuscript'
      fullPath: '/demo/terra/manuscript'
      preLoaderRoute: typeof DemoTerraManuscriptRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/notes': {
      id: '/demo/terra/notes'
      path: '/notes'
      fullPath: '/demo/terra/notes'
      preLoaderRoute: typeof DemoTerraNotesRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/places': {
      id: '/demo/terra/places'
      path: '/places'
      fullPath: '/demo/terra/places'
      preLoaderRoute: typeof DemoTerraPlacesRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/relationships': {
      id: '/demo/terra/relationships'
      path: '/relationships'
      fullPath: '/demo/terra/relationships'
      preLoaderRoute: typeof DemoTerraRelationshipsRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/secrets': {
      id: '/demo/terra/secrets'
      path: '/secrets'
      fullPath: '/demo/terra/secrets'
      preLoaderRoute: typeof DemoTerraSecretsRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/timeline': {
      id: '/demo/terra/timeline'
      path: '/timeline'
      fullPath: '/demo/terra/timeline'
      preLoaderRoute: typeof DemoTerraTimelineRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/worlds/$worldId/manuscript': {
      id: '/worlds/$worldId/manuscript'
      path: '/manuscript'
      fullPath: '/worlds/$worldId/manuscript'
      preLoaderRoute: typeof WorldsWorldIdManuscriptRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/terra/': {
      id: '/worlds/terra/'
      path: '/'
      fullPath: '/worlds/terra/'
      preLoaderRoute: typeof WorldsTerraIndexRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/continuity': {
      id: '/worlds/terra/continuity'
      path: '/continuity'
      fullPath: '/worlds/terra/continuity'
      preLoaderRoute: typeof WorldsTerraContinuityRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/knowledge': {
      id: '/worlds/terra/knowledge'
      path: '/knowledge'
      fullPath: '/worlds/terra/knowledge'
      preLoaderRoute: typeof WorldsTerraKnowledgeRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/lore': {
      id: '/worlds/terra/lore'
      path: '/lore'
      fullPath: '/worlds/terra/lore'
      preLoaderRoute: typeof WorldsTerraLoreRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/manuscript': {
      id: '/worlds/terra/manuscript'
      path: '/manuscript'
      fullPath: '/worlds/terra/manuscript'
      preLoaderRoute: typeof WorldsTerraManuscriptRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/notes': {
      id: '/worlds/terra/notes'
      path: '/notes'
      fullPath: '/worlds/terra/notes'
      preLoaderRoute: typeof WorldsTerraNotesRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/places': {
      id: '/worlds/terra/places'
      path: '/places'
      fullPath: '/worlds/terra/places'
      preLoaderRoute: typeof WorldsTerraPlacesRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/relationships': {
      id: '/worlds/terra/relationships'
      path: '/relationships'
      fullPath: '/worlds/terra/relationships'
      preLoaderRoute: typeof WorldsTerraRelationshipsRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/secrets': {
      id: '/worlds/terra/secrets'
      path: '/secrets'
      fullPath: '/worlds/terra/secrets'
      preLoaderRoute: typeof WorldsTerraSecretsRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/settings': {
      id: '/worlds/terra/settings'
      path: '/settings'
      fullPath: '/worlds/terra/settings'
      preLoaderRoute: typeof WorldsTerraSettingsRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/timeline': {
      id: '/worlds/terra/timeline'
      path: '/timeline'
      fullPath: '/worlds/terra/timeline'
      preLoaderRoute: typeof WorldsTerraTimelineRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/demo/terra/characters/': {
      id: '/demo/terra/characters/'
      path: '/characters'
      fullPath: '/demo/terra/characters/'
      preLoaderRoute: typeof DemoTerraCharactersIndexRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/demo/terra/characters/$slug': {
      id: '/demo/terra/characters/$slug'
      path: '/characters/$slug'
      fullPath: '/demo/terra/characters/$slug'
      preLoaderRoute: typeof DemoTerraCharactersSlugRouteImport
      parentRoute: typeof DemoTerraRoute
    }
    '/worlds/terra/characters/': {
      id: '/worlds/terra/characters/'
      path: '/characters'
      fullPath: '/worlds/terra/characters/'
      preLoaderRoute: typeof WorldsTerraCharactersIndexRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
    '/worlds/terra/characters/$slug': {
      id: '/worlds/terra/characters/$slug'
      path: '/characters/$slug'
      fullPath: '/worlds/terra/characters/$slug'
      preLoaderRoute: typeof WorldsTerraCharactersSlugRouteImport
      parentRoute: typeof WorldsTerraRoute
    }
  }
}

interface DemoTerraRouteChildren {
  DemoTerraContinuityRoute: typeof DemoTerraContinuityRoute
  DemoTerraKnowledgeRoute: typeof DemoTerraKnowledgeRoute
  DemoTerraLoreRoute: typeof DemoTerraLoreRoute
  DemoTerraManuscriptRoute: typeof DemoTerraManuscriptRoute
  DemoTerraNotesRoute: typeof DemoTerraNotesRoute
  DemoTerraPlacesRoute: typeof DemoTerraPlacesRoute
  DemoTerraRelationshipsRoute: typeof DemoTerraRelationshipsRoute
  DemoTerraSecretsRoute: typeof DemoTerraSecretsRoute
  DemoTerraTimelineRoute: typeof DemoTerraTimelineRoute
  DemoTerraIndexRoute: typeof DemoTerraIndexRoute
  DemoTerraCharactersSlugRoute: typeof DemoTerraCharactersSlugRoute
  DemoTerraCharactersIndexRoute: typeof DemoTerraCharactersIndexRoute
}

const DemoTerraRouteChildren: DemoTerraRouteChildren = {
  DemoTerraContinuityRoute: DemoTerraContinuityRoute,
  DemoTerraKnowledgeRoute: DemoTerraKnowledgeRoute,
  DemoTerraLoreRoute: DemoTerraLoreRoute,
  DemoTerraManuscriptRoute: DemoTerraManuscriptRoute,
  DemoTerraNotesRoute: DemoTerraNotesRoute,
  DemoTerraPlacesRoute: DemoTerraPlacesRoute,
  DemoTerraRelationshipsRoute: DemoTerraRelationshipsRoute,
  DemoTerraSecretsRoute: DemoTerraSecretsRoute,
  DemoTerraTimelineRoute: DemoTerraTimelineRoute,
  DemoTerraIndexRoute: DemoTerraIndexRoute,
  DemoTerraCharactersSlugRoute: DemoTerraCharactersSlugRoute,
  DemoTerraCharactersIndexRoute: DemoTerraCharactersIndexRoute,
}

const DemoTerraRouteWithChildren = DemoTerraRoute._addFileChildren(
  DemoTerraRouteChildren,
)

interface WorldsWorldIdRouteChildren {
  WorldsWorldIdManuscriptRoute: typeof WorldsWorldIdManuscriptRoute
}

const WorldsWorldIdRouteChildren: WorldsWorldIdRouteChildren = {
  WorldsWorldIdManuscriptRoute: WorldsWorldIdManuscriptRoute,
}

const WorldsWorldIdRouteWithChildren = WorldsWorldIdRoute._addFileChildren(
  WorldsWorldIdRouteChildren,
)

interface WorldsTerraRouteChildren {
  WorldsTerraContinuityRoute: typeof WorldsTerraContinuityRoute
  WorldsTerraKnowledgeRoute: typeof WorldsTerraKnowledgeRoute
  WorldsTerraLoreRoute: typeof WorldsTerraLoreRoute
  WorldsTerraManuscriptRoute: typeof WorldsTerraManuscriptRoute
  WorldsTerraNotesRoute: typeof WorldsTerraNotesRoute
  WorldsTerraPlacesRoute: typeof WorldsTerraPlacesRoute
  WorldsTerraRelationshipsRoute: typeof WorldsTerraRelationshipsRoute
  WorldsTerraSecretsRoute: typeof WorldsTerraSecretsRoute
  WorldsTerraSettingsRoute: typeof WorldsTerraSettingsRoute
  WorldsTerraTimelineRoute: typeof WorldsTerraTimelineRoute
  WorldsTerraIndexRoute: typeof WorldsTerraIndexRoute
  WorldsTerraCharactersSlugRoute: typeof WorldsTerraCharactersSlugRoute
  WorldsTerraCharactersIndexRoute: typeof WorldsTerraCharactersIndexRoute
}

const WorldsTerraRouteChildren: WorldsTerraRouteChildren = {
  WorldsTerraContinuityRoute: WorldsTerraContinuityRoute,
  WorldsTerraKnowledgeRoute: WorldsTerraKnowledgeRoute,
  WorldsTerraLoreRoute: WorldsTerraLoreRoute,
  WorldsTerraManuscriptRoute: WorldsTerraManuscriptRoute,
  WorldsTerraNotesRoute: WorldsTerraNotesRoute,
  WorldsTerraPlacesRoute: WorldsTerraPlacesRoute,
  WorldsTerraRelationshipsRoute: WorldsTerraRelationshipsRoute,
  WorldsTerraSecretsRoute: WorldsTerraSecretsRoute,
  WorldsTerraSettingsRoute: WorldsTerraSettingsRoute,
  WorldsTerraTimelineRoute: WorldsTerraTimelineRoute,
  WorldsTerraIndexRoute: WorldsTerraIndexRoute,
  WorldsTerraCharactersSlugRoute: WorldsTerraCharactersSlugRoute,
  WorldsTerraCharactersIndexRoute: WorldsTerraCharactersIndexRoute,
}

const WorldsTerraRouteWithChildren = WorldsTerraRoute._addFileChildren(
  WorldsTerraRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DemoTerraRoute: DemoTerraRouteWithChildren,
  WorldsWorldIdRoute: WorldsWorldIdRouteWithChildren,
  WorldsNewRoute: WorldsNewRoute,
  WorldsTerraRoute: WorldsTerraRouteWithChildren,
  WorldsIndexRoute: WorldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
